repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
    - id: yamllint
      args: [--strict]
      exclude: .pre-commit-config|files/|Definitions/|vault
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.3.1
  hooks:
    - id: ansible-lint
      entry: ansible-lint
      additional_dependencies:
        - ansible>=2.9,<2.10
