---
- hosts: proxmox
  gather_facts: yes

  roles:
    - { role: pve/common, tags: [pve, pve_common] }
    - { role: common/packages, tags: [pve, pve_packages] }
    - { role: common/zsh, tags: [pve, pve_zsh] }
    - { role: common/mc, tags: [pve, pve_mc] }
    - { role: common/nano, tags: [pve, pve_nano] }
    - { role: common/motd, tags: [pve, pve_motd] }
    - { role: common/sshd, tags: [pve, pve_sshd] }
    - { role: pve/kernel_modules, tags: [pve, pve_kernel_modules] }
    - { role: pve/postfix, tags: [pve, pve_postfix] }
    - { role: common/snmp, tags: [pve, pve_snmp] }
    - { role: pve/snmp, tags: [pve, pve_snmp] }
    - { role: pve/smartd, tags: [pve, pve_smartd] }
    - { role: common/wireguard, tags: [pve, pve_wireguard] }
