---
- hosts: s-1799-proxy
  gather_facts: yes

  roles:
    - { role: common/wireguard, tags: proxy }
    - { role: services/proxy, tags: proxy }

- hosts: s-1799-glpi
  gather_facts: yes

  vars:
    inventory_env: prod

  roles:
    - { role: common/domain_join, tags: glpi }
    - { role: services/glpi, tags: glpi }

- hosts: s-1799-nms
  gather_facts: yes

  roles:
    - { role: services/nms, tags: nms }

- hosts: mdt
  gather_facts: yes

  roles:
    - { role: services/mdt, tags: mdt }
