---
- hosts: vms
  gather_facts: yes

  roles:
    - { role: common/packages, tags: [vms, packages] }
    - { role: common/zsh, tags: [vms, zsh] }
    - { role: common/mc, tags: [vms, mc] }
    - { role: common/nano, tags: [vms, nano] }
    - { role: common/motd, tags: [vms, motd] }
    - { role: common/sshd, tags: [vps, sshd] }
    - { role: common/snmp, tags: [vms, snmp] }
    - { role: common/docker, tags: [vms, docker] }
