---
- name: Copy /etc/modprobe.d files
  copy:
    src: files/{{ item }}
    dest: /etc/modprobe.d
    mode: 0644
  notify: show reboot msg
  loop:
    - kvm.conf
    - kvm-intel.conf

- name: Copy /etc/modules
  copy:
    src: files/modules
    dest: /etc
    mode: 0644
  notify: show reboot msg

- name: Edit grub config
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
  notify: update-grub
