---
- name: Install packages
  package:
    state: present
    name:
      - nagios-nrpe-server
      - sudo

- name: Download check_lsi_raid plugin
  get_url:
    url: "{{ nrpe_plugin_source }}"
    dest: "{{ nrpe_plugins_path }}"
    mode: a+x

- name: Configure nrpe allowed hosts
  lineinfile:
    path: "{{ nrpe_config_path }}"
    regexp: "^allowed_hosts="
    line: allowed_hosts=127.0.0.1,::1,{{ nrpe_allowed_host }}
  notify: restart nagios-nrpe-server

- name: Add check command
  lineinfile:
    path: "{{ nrpe_config_path }}"
    line: command[check_lsi_raid]={{ nrpe_plugins_path }}/check_lsi_raid -C 0 -p {{ storcli_symlink }}
    state: present
  notify: restart nagios-nrpe-server

- name: Copy sudoers.d file
  copy:
    src: files/nagios_sudo
    dest: /etc/sudoers.d
    mode: 0440
