---
- name: Check if storcli installed
  command: dpkg-query -W storcli
  ignore_errors: True
  register: storcli_is_installed
  changed_when: storcli_is_installed.rc != 0

- block:
    - name: Copy package
      copy:
        src: files/{{ storcli_package_name }}
        dest: /tmp
        mode: 0644

    - name: Install package
      package:
        deb: /tmp/{{ storcli_package_name }}
        state: present

    - name: Create symlink
      file:
        src: /opt/MegaRAID/storcli/storcli64
        dest: /usr/local/sbin/storcli
        state: link
  when: storcli_version not in storcli_is_installed.stdout
