---
- name: Configure static routes (works in 1799-6 network only!)
  interfaces_file:
    iface: ens18
    option: up
    value: ip -4 route add {{ item }} via 172.19.8.1
  notify: restart networking
  loop:
    - 10/8
    - 172.28.236.0/23
    - 172.18.248.0/23
    - 172.19.0.0/23
    - 172.19.4.0/23
    - 194.135.112.139/32
    - 213.79.88.191/32

- name: wireguard tasks
  include_tasks: wireguard.yml

- name: Create a docker network
  docker_network:
    name: "{{ app_network_name }}"
    ipam_config:
      - subnet: 172.31.254.0/24

- name: portainer
  include_tasks: portainer.yml

- name: nginx-proxy-manager
  include_tasks: nginx-proxy-manager.yml
