---
- name: nginx-proxy-manager-db - start
  docker_container:
    name: nginx-proxy-manager-db
    image: "{{ npm_db_image }}"
    pull: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ npm_db_root_pass }}"
      MYSQL_DATABASE: "{{ npm_db_user }}"
      MYSQL_USER: "{{ npm_db_user }}"
      MYSQL_PASSWORD: "{{ npm_db_pass }}"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_unicode_ci"
    volumes:
      - "{{ app_path }}/nginx-proxy-manager/db:/var/lib/mysql"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    state: started
  notify: restart nginx-proxy-manager
  no_log: true

- name: nginx-proxy-manager - create dir
  file:
    path: "{{ app_path }}/nginx-proxy-manager/app/data/nginx"
    state: directory
    recurse: yes

- name: nginx-proxy-manager - copy files
  copy:
    src: files/custom
    dest: "{{ app_path }}/nginx-proxy-manager/app/data/nginx"
    mode: 0644
    directory_mode: 0755
  notify: restart nginx-proxy-manager

- name: nginx-proxy-manager - start
  docker_container:
    name: nginx-proxy-manager
    image: "{{ npm_image }}"
    pull: yes
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    env:
      DB_MYSQL_HOST: "nginx-proxy-manager-db"
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: "{{ npm_db_user }}"
      DB_MYSQL_PASSWORD: "{{ npm_db_pass }}"
      DB_MYSQL_NAME: "{{ npm_db_user }}"
      DISABLE_IPV6: "true"
    volumes:
      - "{{ app_path }}/nginx-proxy-manager/app/data:/data"
      - "{{ app_path }}/nginx-proxy-manager/app/letsencrypt:/etc/letsencrypt"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    state: started
  register: npm_start
