---
- name: wireguard - install packages
  package:
    state: present
    name:
      - iptables-persistent

- name: wireguard - create directories
  file:
    path: "{{ wg_path }}"
    state: directory
    mode: 0700

- name: wireguard - copy wg0 configuration
  template:
    src: wg0.conf.j2
    dest: "{{ wg_path }}/wg0.conf"
    mode: 0600
  no_log: true
  notify: restart wireguard

- name: wireguard - configure iptables - forwarding
  iptables:
    chain: FORWARD
    in_interface: "{{ item }}"
    jump: ACCEPT
    action: insert
    comment: "forwarding for {{ item }}"
  notify: save iptables
  loop: "{{ iptables_interfaces }}"

- name: wireguard - configure iptables - masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ item }}"
    jump: MASQUERADE
    action: insert
    comment: "masquerade for {{ item }}"
  notify: save iptables
  loop: "{{ iptables_interfaces }}"
