---
- name: restart wireguard
  service:
    name: wg-quick@wg0
    enabled: yes
    state: restarted

- name: restart networking
  service:
    name: networking
    state: restarted

- name: restart iptables
  service:
    name: netfilter-persistent
    state: restarted

- name: restart docker
  service:
    name: docker
    state: restarted
  listen: restart iptables

- name: restart nginx-proxy-manager
  docker_container:
    name: nginx-proxy-manager
    state: started
    restart: yes
  no_log: true
  when: not npm_start.changed
